name: Prep OTEL source

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.6'

      - name: Check golang version
        run: go version
